"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['brac_sync.py']
DATA_FILES = ['../resources/arr_down.png',
 '../resources/arr_right(128x128).png',
 '../resources/arr_right.png',
 '../resources/arr_up.png',
 '../resources/brac-128x128.png',
 '../resources/brac-16x16.png',
 '../resources/brac-32x32.png',
 '../resources/brac-64x64.png',
 '../resources/brac-syncing-16x16.png',
 '../resources/brac.png',
 '../resources/dir.png',
 '../resources/file.png',
 '../resources/remove.png',
 '../resources/sync_notice.png',
 '../resources/sync_started.png',
 '../resources/sync_stopped.png',
 'dialog_settings.ui']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
