"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['brac-browser.py']
DATA_FILES = ['../resources/background.jpg',
 '../resources/no-image.gif',
 '../resources/transparent_checkerboard_square_125.png',
 'brac-browser.ui']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
